from enum import Enum

__all__ = ["MissionType"]


class MissionType(Enum):
    AncientRetribution = "Ancient Retribution"
    Arena = "Arena"
    Assassination = "Assassination"
    Assault = "Assault"
    Capture = "Capture"
    Conclave = "Conclave"
    DarkSectorDefection = "Dark Sector Defection"
    DarkSectorDefense = "Dark Sector Defense"
    DarkSectorDisruption = "Dark Sector Disruption"
    DarkSectorExcavation = "Dark Sector Excavation"
    DarkSectorSabotage = "Dark Sector Sabotage"
    DarkSectorSurvival = "Dark Sector Survival"
    Defense = "Defense"
    Disruption = "Disruption"
    Excavation = "Excavation"
    ExterminationArchwing = "Extermination (Archwing)"
    Extermination = "Extermination"
    FreeRoam = "Free Roam"
    Hijack = "Hijack"
    Hive = "Hive"
    HiveSabotage = "Hive Sabotage"
    Interception = "Interception"
    InterceptionArchwing = "Interception (Archwing)"
    MobileDefense = "Mobile Defense"
    MobileDefenseArchwing = "Mobile Defense (Archwing)"
    OrokinSabotage = "Orokin Sabotage"
    Orphix = "Orphix"
    PursuitArchwing = "Pursuit (Archwing)"
    Relay = "Relay"
    Rescue = "Rescue"
    RushArchwing = "Rush (Archwing)"
    Sabotage = "Sabotage"
    SabotageArchwing = "Sabotage (Archwing)"
    Skirmish = "Skirmish"
    Spy = "Spy"
    Survival = "Survival"
    Volatile = "Volatile"
